day2/Auction_site/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    resources :products do
      resources :bids
    end
  end


  get 'profile', to: 'users#profile'
  root to: 'users#profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

day2/Auction_site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

day2/Auction_site/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

day2/Auction_site/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  has_many :bids
  has_many :users, through: :bids

end

day2/Auction_site/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bids
  has_many :products, through: :bids

  has_many :owned_products, source: :products
end

day2/Auction_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

day2/Auction_site/app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  def index
    @product = Product.find(params[:product_id])
    @bids = Bid.where(product: @product)
  end

  # GET /bids/1
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  def create
    @user = User.find(params[:user_id])
    @product = Product.find(params[:product_id])
    @bid = Bid.new({user: @user, product: @product})
    @bid.update(bid_params)

    #raise @user.inspect
    #raise @bid.inspect
    if @bid.save
      redirect_to action: 'index', controller: 'products', user: @user
    else
      render 'new'
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:amount)
    end
end

day2/Auction_site/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.find(params[:user_id])

    # @products = Product.where(user_id: @user)
    @products = Product.all
  end

  def new
    @user = User.find(params[:user_id])
    # @product = Product.new
    @product = @user.products.new

  end

  def create

    #raise.params.inspect
    # raise params.inspect
    # par = product_params
    # par.push(params.require(:product).permit(:user_id))
    # @user = User.find(params[:user_id])
    #@product = Product.new(user: @user)

    @user = User.where({name: 'undefinded'})
    @product = Product.new({user_id:4})
    @product.update(product_params)

    #raise @user.inspect

    if @product.save

      redirect_to action: 'index', controller: 'products', user: @user
    else
      render 'new'
    end

  end

  def show
    @user = User.find(params[:user_id])
    @product = Product.find(params[:id])

    @bid = Bid.new(product: @product, user: @user)
    @bids = Bid.where(product: @product)

    if @product.deadline > Date.today
      max_amount = @bids.maximum(:amount)
      user = @bids.where(amount: max_amount).pluck(:user_id)

      @product.update({user_id: 2})
      #raise @product.inspect
    end

    @winner_user = @product.user
    
    # @bid = Bid.new(product_id_id: @product)

  end


  def destroy
    @product.destroy
    redirect_to products_path, notice: 'Product was successfully destroyed.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :deadline)
    end
end

day2/Auction_site/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def profile
    @user = current_user
    render 'users/profile'
  end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

day2/Auction_site/app/helpers/application_helper.rb
module ApplicationHelper
end

day2/Auction_site/app/helpers/bids_helper.rb
module BidsHelper
end

day2/Auction_site/app/helpers/products_helper.rb
module ProductsHelper
end

day2/Auction_site/app/helpers/users_helper.rb
module UsersHelper
end

day2/Auction_site/app/views/layouts/_logged_menu.html.erb
<div id="top_bar">
<% if user_signed_in? %>
  <p><%= link_to 'Sign out', destroy_user_session_path, method:'DELETE' %></p>
<% else %>
  <p>
    <%= link_to 'Sign_up', new_user_registration_path %> |
    <%= link_to 'Sign_in', new_user_session_path %>
  </p>
<% end %>
</div>

day2/Auction_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionSite2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'layouts/logged_menu'%>

    <%= yield %>
  </body>
</html>

day2/Auction_site/app/views/products/index.html.erb
<h4>User: <%= @user.name %> </h4>


<ul>
  <% @products.each do |product| %>

    <li>  <%=  link_to product.title, user_product_path(@user , product) %>

    </li>

  <% end %>
  </ul>

<%= link_to 'New Product', new_user_product_path %>

day2/Auction_site/app/views/products/new.html.erb
<%= form_for([ @user, @product]) do |f| %>

  <h2>New product: </h2>

  <%= f.label :title  %>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :description  %>
  <%= f.text_area :description %>

  <br>
  <br>

  <!-- <%= date_field("product", :deadline) %> -->

  <!-- <%= date_select("product", "deadline", use_month_numbers: true, use_days_numbers: true ,start_year: 1995,
                                   include_blank: true) %> -->

  <%=date_field("product", :deadline, min: Date.today)%>

  <br>
  <br>



  <div class="field">
  <%= f.label :user_id %><br>
  <%=  @user.name%>
</div>


  <br>
  <br>


  <%= f.submit %>
<% end %>

day2/Auction_site/app/views/products/show.html.erb
<h3>Product</h3>

<p> Title: <%= @product.title%></p>
<p> Description <%= @product.description  %></p>
<p> Deadline <%= @product.deadline  %></p>
<% if @product.user_id != 4 %>
  <p> User: <%= link_to @winner_user.name , user_path(@winner_user) %> </p>
<% else %>

  <div>
    <h4>Bids:</h4>
    <% @bids.each do |bid| %>
      <%= bid.user.name%> => <%= bid.amount %>$ <br>
    <% end %>
  </div>

  <div>
    <h5>New bid:</h5>
    <%= render "bids/form" %>
  </div>
  <br>
<% end %>



<%= link_to 'Back', user_products_path(@user) %>

day2/Auction_site/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

day2/Auction_site/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

day2/Auction_site/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

day2/Auction_site/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

day2/Auction_site/app/views/users/profile.html.erb
 <%# app/views/users/profile.html.erb %>
 <h2><%= current_user.name %>!</h2>
 <p>
 <strong>Email:</strong> <%= current_user.email %>
 </p>

day2/Auction_site/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>